### PR TITLE
Update protobuf schema to 3.0.1

### PR DESCRIPTION
**Pull request by huttmf**
Updated the protobuf schema to use the file from 3.0.1.

### CODE REVIEW

**Comment by jpsenior** [comment]
I don't recall @huttmf is this .go template automatically built by AOS?

**Comment by huttmf** [comment]
No - this comes from compiling aosstream.proto with protoc.

**Review by Ragsboss — APPROVED** [review]
Can you add instructions on how to maintain this file somewhere?

**Comment by jpsenior** [comment]
Yes, I was wondering if we could just include generation of the schema as part of our product build and save it as an artifact.

**Comment by huttmf** [comment]
If we have protoc in the build env then we can just run:
`protoc --go_out=. aosstream.proto`

**Pull request merged**
